# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'abcNotepad.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        Form.setMinimumSize(QtCore.QSize(1080, 720))
        Form.setMaximumSize(QtCore.QSize(1080, 720))
        Form.setWindowIcon(QtGui.QIcon('./image/icon.png'))
        Form.setStyleSheet("color:rgb(171, 168, 162)")
        self.save = QtWidgets.QPushButton(Form)
        self.save.setGeometry(QtCore.QRect(10, 10, 32, 32))
        self.save.setStyleSheet("border-image:url(./image/save.png)")
        self.save.setObjectName("save")
        self.open = QtWidgets.QPushButton(Form)
        self.open.setGeometry(QtCore.QRect(50, 10, 32, 32))
        self.open.setStyleSheet("border-image:url(./image/open.png)")
        self.open.setObjectName("open")
        self.add = QtWidgets.QPushButton(Form)
        self.add.setGeometry(QtCore.QRect(90, 10, 32, 32))
        self.add.setStyleSheet("border-image:url(./image/new.png)")
        self.add.setObjectName("add")
        self.history = QtWidgets.QPushButton(Form)
        self.history.setGeometry(QtCore.QRect(130, 10, 32, 32))
        self.history.setStyleSheet("border-image:url(./image/history.png)")
        self.history.setObjectName("history")
        self.setting = QtWidgets.QPushButton(Form)
        self.setting.setGeometry(QtCore.QRect(1040, 10, 32, 32))
        self.setting.setStyleSheet("border-image:url(./image/setting.png)")
        self.setting.setObjectName("setting")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 10, 861, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background:rgb(211, 230, 255)")
        self.label.setObjectName("label")
        self.folder = QtWidgets.QPushButton(Form)
        self.folder.setGeometry(QtCore.QRect(990, 10, 33, 31))
        self.folder.setStyleSheet("border-image:url(./image/open.png)")
        self.folder.setObjectName("folder")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 50, 1061, 621))
        self.textEdit.setObjectName("textEdit")
        self.find = QtWidgets.QPushButton(Form)
        self.find.setGeometry(QtCore.QRect(10, 680, 37, 31))
        self.find.setStyleSheet("border-image:url(./image/find.png)")
        self.find.setObjectName("find")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "abcNotebook"))
        self.label.setText(_translate("Form", "(无)"))
